table 'All Projects'
	lineageTag: 91aa170f-dd80-462f-aa9d-92d4b13d309e

	column 'tasks.id'
		dataType: string
		lineageTag: 0f59bfed-4840-494f-8d23-c13d34ef4876
		summarizeBy: none
		sourceColumn: tasks.id

		annotation SummarizationSetBy = Automatic

	column 'tasks.custom_id'
		dataType: string
		isHidden
		lineageTag: aee82682-2838-4030-b5bc-d3498f782898
		summarizeBy: none
		sourceColumn: tasks.custom_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.custom_item_id'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: fa7422b3-2578-442d-ac40-f4d99f284b91
		summarizeBy: sum
		sourceColumn: tasks.custom_item_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.name'
		dataType: string
		lineageTag: f96224ae-d089-4807-96a8-02286f57d9e7
		summarizeBy: none
		sourceColumn: tasks.name

		annotation SummarizationSetBy = Automatic

	column 'tasks.text_content'
		dataType: string
		lineageTag: 71b435f4-d5bb-4da0-84f5-83742edaa72a
		summarizeBy: none
		sourceColumn: tasks.text_content

		annotation SummarizationSetBy = Automatic

	column 'tasks.description'
		dataType: string
		lineageTag: 264cdcb5-23ca-407e-ae8a-c615dec9b2b5
		summarizeBy: none
		sourceColumn: tasks.description

		annotation SummarizationSetBy = Automatic

	column 'tasks.status.status'
		dataType: string
		lineageTag: 3e33fe40-ef07-4fbf-bf46-9e37afb957d1
		summarizeBy: none
		sourceColumn: tasks.status.status

		annotation SummarizationSetBy = Automatic

	column 'tasks.status.id'
		dataType: string
		lineageTag: 5b6feb23-aa38-45a5-93cf-1dee1cb99d13
		summarizeBy: none
		sourceColumn: tasks.status.id

		annotation SummarizationSetBy = Automatic

	column 'tasks.status.color'
		dataType: string
		lineageTag: 304f4b83-97a1-4f22-a21d-531df1966cd0
		summarizeBy: none
		sourceColumn: tasks.status.color

		annotation SummarizationSetBy = Automatic

	column 'tasks.status.type'
		dataType: string
		lineageTag: 76cf2b94-6f29-49e9-9f9c-36bb5b4de82a
		summarizeBy: none
		sourceColumn: tasks.status.type

		annotation SummarizationSetBy = Automatic

	column 'tasks.status.orderindex'
		dataType: int64
		formatString: 0
		lineageTag: b8fa668a-3836-4418-8715-5cd85e57ead6
		summarizeBy: sum
		sourceColumn: tasks.status.orderindex

		annotation SummarizationSetBy = Automatic

	column 'tasks.orderindex'
		dataType: double
		lineageTag: a2347a3f-7bfa-468d-b9c9-29fdddda6db9
		summarizeBy: sum
		sourceColumn: tasks.orderindex

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'tasks.date_created'
		dataType: int64
		formatString: 0
		lineageTag: 79b49b0c-8ab9-4fed-80be-e1224691fc02
		summarizeBy: sum
		sourceColumn: tasks.date_created

		annotation SummarizationSetBy = Automatic

	column 'tasks.date_updated'
		dataType: int64
		formatString: 0
		lineageTag: 1390eeae-53e1-45ae-b012-45f8483bea5d
		summarizeBy: sum
		sourceColumn: tasks.date_updated

		annotation SummarizationSetBy = Automatic

	column 'tasks.date_closed'
		dataType: string
		lineageTag: d4ee33e6-ecca-4c92-be1b-de56995e0524
		summarizeBy: none
		sourceColumn: tasks.date_closed

		annotation SummarizationSetBy = Automatic

	column 'tasks.date_done'
		dataType: string
		lineageTag: 3ec64186-9ad5-4948-85ea-2944db764a3a
		summarizeBy: none
		sourceColumn: tasks.date_done

		annotation SummarizationSetBy = Automatic

	column 'tasks.archived'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 88e2b368-e7cc-4fdc-9c5c-583c3c7b37f5
		summarizeBy: none
		sourceColumn: tasks.archived

		annotation SummarizationSetBy = Automatic

	column 'tasks.creator.id'
		dataType: int64
		formatString: 0
		lineageTag: b6248439-3bd3-45c6-ba0f-e9e3e922f0fb
		summarizeBy: sum
		sourceColumn: tasks.creator.id

		annotation SummarizationSetBy = Automatic

	column 'tasks.creator.username'
		dataType: string
		lineageTag: 12a69d89-ef8c-43e2-98f0-1dae157aef9a
		summarizeBy: none
		sourceColumn: tasks.creator.username

		annotation SummarizationSetBy = Automatic

	column 'tasks.creator.color'
		dataType: string
		lineageTag: 932ca669-8248-4bb2-b198-6e081203b17b
		summarizeBy: none
		sourceColumn: tasks.creator.color

		annotation SummarizationSetBy = Automatic

	column 'tasks.creator.email'
		dataType: string
		lineageTag: 7b61a320-05f1-4ed8-acf0-86de4aee5285
		summarizeBy: none
		sourceColumn: tasks.creator.email

		annotation SummarizationSetBy = Automatic

	column 'tasks.creator.profilePicture'
		dataType: string
		lineageTag: bd3c13c0-90a5-459d-90cd-80abb9ec5d5f
		summarizeBy: none
		sourceColumn: tasks.creator.profilePicture

		annotation SummarizationSetBy = Automatic

	column 'tasks.group_assignees'
		dataType: string
		lineageTag: e1f9102d-4210-43f3-9878-6b4d5b46e211
		summarizeBy: none
		sourceColumn: tasks.group_assignees

		annotation SummarizationSetBy = Automatic

	column 'tasks.watchers'
		dataType: string
		lineageTag: c3f7fd31-9787-493f-bd45-9ac9b4a68d4d
		summarizeBy: none
		sourceColumn: tasks.watchers

		annotation SummarizationSetBy = Automatic

	column 'tasks.checklists'
		dataType: string
		lineageTag: daf98234-2248-470f-be1e-070824796a19
		summarizeBy: none
		sourceColumn: tasks.checklists

		annotation SummarizationSetBy = Automatic

	column 'tasks.parent'
		dataType: string
		lineageTag: d635efe7-4a0c-4f19-b8ae-c0c52dd18b86
		summarizeBy: none
		sourceColumn: tasks.parent

		annotation SummarizationSetBy = Automatic

	column 'tasks.due_date'
		dataType: int64
		formatString: 0
		lineageTag: 3cad276d-97db-4488-a043-18b2ecac1ab3
		summarizeBy: sum
		sourceColumn: tasks.due_date

		annotation SummarizationSetBy = Automatic

	column 'tasks.start_date'
		dataType: string
		lineageTag: 9be846d4-f767-43d0-b0b7-14bcdd4744e3
		summarizeBy: none
		sourceColumn: tasks.start_date

		annotation SummarizationSetBy = Automatic

	column 'tasks.points'
		dataType: string
		lineageTag: f3f7aba1-8e2a-4fd3-84e9-ddb29091f1b8
		summarizeBy: none
		sourceColumn: tasks.points

		annotation SummarizationSetBy = Automatic

	column 'tasks.time_estimate'
		dataType: string
		lineageTag: 3070e5d1-1bdc-40c5-a3b8-3e8530558523
		summarizeBy: none
		sourceColumn: tasks.time_estimate

		annotation SummarizationSetBy = Automatic

	column 'tasks.custom_fields'
		dataType: string
		lineageTag: 5b8d010a-dade-4cbb-847d-eb0e83f8c70e
		summarizeBy: none
		sourceColumn: tasks.custom_fields

		annotation SummarizationSetBy = Automatic

	column 'tasks.dependencies'
		dataType: string
		lineageTag: a054a8f3-659c-4199-b6a4-c359c89fd61a
		summarizeBy: none
		sourceColumn: tasks.dependencies

		annotation SummarizationSetBy = Automatic

	column 'tasks.linked_tasks'
		dataType: string
		lineageTag: c60ccfc3-57a2-4f9e-899a-dcde2530a5a8
		summarizeBy: none
		sourceColumn: tasks.linked_tasks

		annotation SummarizationSetBy = Automatic

	column 'tasks.locations'
		dataType: string
		lineageTag: 1110a8cc-1568-45d2-9ba7-a9ee14febe9f
		summarizeBy: none
		sourceColumn: tasks.locations

		annotation SummarizationSetBy = Automatic

	column 'tasks.team_id'
		dataType: int64
		formatString: 0
		lineageTag: 3da8d354-bc46-4811-b054-ba2d62ff3646
		summarizeBy: sum
		sourceColumn: tasks.team_id

		annotation SummarizationSetBy = Automatic

	column 'tasks.url'
		dataType: string
		lineageTag: 2d210998-63bc-4524-ab28-cbe8e05404d1
		summarizeBy: none
		sourceColumn: tasks.url

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ce32cadf-8ff0-4ada-b4f2-b7c26d7ec73e
		summarizeBy: none
		sourceColumn: tasks.sharing.public

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public_share_expires_on'
		dataType: string
		lineageTag: f2464b05-7a84-44f5-81da-20f68d27f4f7
		summarizeBy: none
		sourceColumn: tasks.sharing.public_share_expires_on

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public_fields.0'
		dataType: string
		lineageTag: 3ea25014-0900-420d-a193-4abf585239ba
		summarizeBy: none
		sourceColumn: tasks.sharing.public_fields.0

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public_fields.1'
		dataType: string
		lineageTag: 49d09af4-d244-4acf-9c1c-7725b851a92d
		summarizeBy: none
		sourceColumn: tasks.sharing.public_fields.1

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public_fields.2'
		dataType: string
		lineageTag: cd9e0ee3-1993-4095-be41-dcc89347d900
		summarizeBy: none
		sourceColumn: tasks.sharing.public_fields.2

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public_fields.3'
		dataType: string
		lineageTag: 6579441c-2bf4-47a2-89f8-a62e63bc7dc4
		summarizeBy: none
		sourceColumn: tasks.sharing.public_fields.3

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public_fields.4'
		dataType: string
		lineageTag: dac96454-535c-42af-a585-f8c8c583265e
		summarizeBy: none
		sourceColumn: tasks.sharing.public_fields.4

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public_fields.5'
		dataType: string
		lineageTag: 1c28335b-adbc-4ce1-80df-e8266334f89a
		summarizeBy: none
		sourceColumn: tasks.sharing.public_fields.5

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public_fields.6'
		dataType: string
		lineageTag: 57d493f7-59e8-44b0-ad7f-ebd84fa69861
		summarizeBy: none
		sourceColumn: tasks.sharing.public_fields.6

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public_fields.7'
		dataType: string
		lineageTag: e074829f-9d76-4484-abae-ba522bdc0576
		summarizeBy: none
		sourceColumn: tasks.sharing.public_fields.7

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public_fields.8'
		dataType: string
		lineageTag: b1a1149b-4acc-445c-a34b-ee61ef352bd2
		summarizeBy: none
		sourceColumn: tasks.sharing.public_fields.8

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public_fields.9'
		dataType: string
		lineageTag: a0fcfd9b-15a5-484e-9c25-0a7947c37ad4
		summarizeBy: none
		sourceColumn: tasks.sharing.public_fields.9

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public_fields.10'
		dataType: string
		lineageTag: 4aed865f-95d4-4eb4-aff3-a2e9e6f74854
		summarizeBy: none
		sourceColumn: tasks.sharing.public_fields.10

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.token'
		dataType: string
		lineageTag: 1f0978f9-cc46-452f-babf-ef76ee4bd026
		summarizeBy: none
		sourceColumn: tasks.sharing.token

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.seo_optimized'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 57d2d6af-ef15-45ba-a25b-01477fa7f290
		summarizeBy: none
		sourceColumn: tasks.sharing.seo_optimized

		annotation SummarizationSetBy = Automatic

	column 'tasks.permission_level'
		dataType: string
		lineageTag: 0e6f39f2-a138-4728-911e-6c340504e7e1
		summarizeBy: none
		sourceColumn: tasks.permission_level

		annotation SummarizationSetBy = Automatic

	column 'tasks.list.id'
		dataType: int64
		formatString: 0
		lineageTag: aa350ab9-bd1c-44e2-b64e-d989a6e50a15
		summarizeBy: sum
		sourceColumn: tasks.list.id

		annotation SummarizationSetBy = Automatic

	column 'tasks.list.name'
		dataType: string
		lineageTag: 3651e000-f84a-48cd-aa85-d4274660720f
		summarizeBy: none
		sourceColumn: tasks.list.name

		annotation SummarizationSetBy = Automatic

	column 'tasks.list.access'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 64a413a0-599f-4f5a-908c-2250f0f833a5
		summarizeBy: none
		sourceColumn: tasks.list.access

		annotation SummarizationSetBy = Automatic

	column 'tasks.project.id'
		dataType: int64
		formatString: 0
		lineageTag: a3d5c636-1fe7-41d9-b64d-722bcb0dd951
		summarizeBy: sum
		sourceColumn: tasks.project.id

		annotation SummarizationSetBy = Automatic

	column 'tasks.project.name'
		dataType: string
		lineageTag: 278e5c8b-accf-4732-8772-fa5ad5fefe8e
		summarizeBy: none
		sourceColumn: tasks.project.name

		annotation SummarizationSetBy = Automatic

	column 'tasks.project.hidden'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 15e488c3-3417-47e9-9519-7f9f65790c70
		summarizeBy: none
		sourceColumn: tasks.project.hidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.project.access'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 1f228aa7-7705-4c4c-9422-bd6ca693407a
		summarizeBy: none
		sourceColumn: tasks.project.access

		annotation SummarizationSetBy = Automatic

	column 'tasks.folder.id'
		dataType: int64
		formatString: 0
		lineageTag: 96861c67-0ad0-469f-ada1-906a56edb25a
		summarizeBy: sum
		sourceColumn: tasks.folder.id

		annotation SummarizationSetBy = Automatic

	column 'tasks.folder.name'
		dataType: string
		lineageTag: 2cff6ce9-ff89-4c67-ac23-d5fa35a9ff6c
		summarizeBy: none
		sourceColumn: tasks.folder.name

		annotation SummarizationSetBy = Automatic

	column 'tasks.folder.hidden'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 1bb2c744-7713-463a-ac35-0358907f4be1
		summarizeBy: none
		sourceColumn: tasks.folder.hidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.folder.access'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 89180e51-71e5-41b3-b56c-d85901252930
		summarizeBy: none
		sourceColumn: tasks.folder.access

		annotation SummarizationSetBy = Automatic

	column 'tasks.space.id'
		dataType: int64
		formatString: 0
		lineageTag: edf4522e-5aac-4239-94d6-07cd2971a5cd
		summarizeBy: sum
		sourceColumn: tasks.space.id

		annotation SummarizationSetBy = Automatic

	column last_page
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e60c5c7e-4337-417a-827b-68fbf4e7a81d
		summarizeBy: none
		sourceColumn: last_page

		annotation SummarizationSetBy = Automatic

	column 'tasks.time_spent'
		dataType: int64
		formatString: 0
		lineageTag: d4a27659-48f1-4ebb-a8aa-0e7d835410b5
		summarizeBy: sum
		sourceColumn: tasks.time_spent

		annotation SummarizationSetBy = Automatic

	column 'tasks.priority.color'
		dataType: string
		lineageTag: 0d17acff-7546-4434-962f-f3f99bd0173d
		summarizeBy: none
		sourceColumn: tasks.priority.color

		annotation SummarizationSetBy = Automatic

	column 'tasks.priority.id'
		dataType: int64
		formatString: 0
		lineageTag: 8371dd73-d5b1-4b73-a3e6-08a69171c72e
		summarizeBy: sum
		sourceColumn: tasks.priority.id

		annotation SummarizationSetBy = Automatic

	column 'tasks.priority.orderindex'
		dataType: int64
		formatString: 0
		lineageTag: d91336c8-555d-4f56-9700-52e2cb1fd40c
		summarizeBy: sum
		sourceColumn: tasks.priority.orderindex

		annotation SummarizationSetBy = Automatic

	column 'tasks.priority.priority'
		dataType: string
		lineageTag: 6aeb0e68-7385-4a15-9790-905c454503d8
		summarizeBy: none
		sourceColumn: tasks.priority.priority

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public_fields'
		dataType: string
		lineageTag: 090e80d7-0237-4f7a-97b2-9746bc972d27
		summarizeBy: none
		sourceColumn: tasks.sharing.public_fields

		annotation SummarizationSetBy = Automatic

	column 'tasks.assignees.username'
		dataType: string
		lineageTag: 8c79541b-ae6c-4624-b000-cc0b787ebad4
		summarizeBy: none
		sourceColumn: tasks.assignees.username

		annotation SummarizationSetBy = Automatic

	column 'tasks.tags.name'
		dataType: string
		lineageTag: b6590bca-d6f0-493d-bac9-3799d7c77782
		summarizeBy: none
		sourceColumn: tasks.tags.name

		annotation SummarizationSetBy = Automatic

	column 'tasks.priority.priority.1'
		dataType: string
		lineageTag: 08e16717-ef8e-4a27-a262-89ba123d5155
		summarizeBy: none
		sourceColumn: tasks.priority.priority.1

		annotation SummarizationSetBy = Automatic

	column 'Due Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: fd2d3ea7-a916-44b5-905f-46672b53676d
		summarizeBy: none
		sourceColumn: Due Date

		variation Variation
			isDefault
			relationship: 07fbc8b7-41be-4883-a75e-e77d25d7edcf
			defaultHierarchy: LocalDateTable_b78d6133-cdbc-4f02-a544-39f4f54ca567.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Date Created'
		dataType: dateTime
		formatString: Short Date
		lineageTag: ff923987-c49a-4010-b8c5-9b854c44b43e
		summarizeBy: none
		sourceColumn: Date Created

		variation Variation
			isDefault
			relationship: 70f3afb4-5c9d-4932-8744-fb024263e8b4
			defaultHierarchy: LocalDateTable_8a2e3f90-a6f6-4558-a786-6dc67659197d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'All Projects' = m
		mode: import
		source =
				let
				    Source = Table.Combine({Operations, BioQuintex, #"BossPet Edge", #"Express Flooring", Flowgistics, #"Full Circle", #"Cognitive Research Corporation", #"JasBo Technologies", Hermanson, #"ITW Medical", #"Lansing Water & Electric", #"ETC Institute"}),
				    #"Expanded tasks.assignees" = Table.ExpandListColumn(Source, "tasks.assignees"),
				    #"Expanded tasks.assignees1" = Table.ExpandRecordColumn(#"Expanded tasks.assignees", "tasks.assignees", {"username"}, {"tasks.assignees.username"}),
				    #"Expanded tasks.tags" = Table.ExpandListColumn(#"Expanded tasks.assignees1", "tasks.tags"),
				    #"Expanded tasks.tags1" = Table.ExpandRecordColumn(#"Expanded tasks.tags", "tasks.tags", {"name"}, {"tasks.tags.name"}),
				    #"Expanded tasks.priority" = Table.ExpandRecordColumn(#"Expanded tasks.tags1", "tasks.priority", {"priority"}, {"tasks.priority.priority.1"}),
				    #"Added Custom" = Table.AddColumn(#"Expanded tasks.priority", "Due Date", each if [tasks.due_date] = null then null else #datetime(1970, 1, 1, 0, 0, 0) + #duration(0, 0, 0, [tasks.due_date]/1000)),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Date Created", each if [tasks.date_created] = null then null else #datetime(1970, 1, 1, 0, 0, 0) + #duration(0, 0, 0, [tasks.date_created]/1000)),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom1",{{"Date Created", type date}, {"Due Date", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

