table 'Cognitive Research Corporation'
	isHidden
	lineageTag: 06ae6db8-11b7-4a1d-b4b6-f57fcb779d24

	column 'tasks.id'
		dataType: string
		isHidden
		lineageTag: 4d6793a6-aced-413d-8776-42e3e97448b4
		summarizeBy: none
		sourceColumn: tasks.id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.custom_id'
		dataType: string
		isHidden
		lineageTag: 53ba92cd-8b81-47aa-baf5-d027a024ce9e
		summarizeBy: none
		sourceColumn: tasks.custom_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.custom_item_id'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 03bd29b5-99b0-48a9-a156-7e098336711b
		summarizeBy: sum
		sourceColumn: tasks.custom_item_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.name'
		dataType: string
		isHidden
		lineageTag: 2f11f060-eebc-4a2a-8f5b-e95f1b9589db
		summarizeBy: none
		sourceColumn: tasks.name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.text_content'
		dataType: string
		isHidden
		lineageTag: 902eeff7-1967-41b6-9bc7-7d42296523c3
		summarizeBy: none
		sourceColumn: tasks.text_content

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.description'
		dataType: string
		isHidden
		lineageTag: 89ba64dd-005a-4421-aeb7-3b12129a4483
		summarizeBy: none
		sourceColumn: tasks.description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.status.status'
		dataType: string
		isHidden
		lineageTag: 815a7089-6d20-4a92-aa00-359cdc38f8f4
		summarizeBy: none
		sourceColumn: tasks.status.status

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.status.id'
		dataType: string
		isHidden
		lineageTag: ee41fa6c-f6b1-4d7a-91c2-3bf4f8e95fec
		summarizeBy: none
		sourceColumn: tasks.status.id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.status.color'
		dataType: string
		isHidden
		lineageTag: aae4d1fc-a17c-483d-a765-a4172abe7273
		summarizeBy: none
		sourceColumn: tasks.status.color

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.status.type'
		dataType: string
		isHidden
		lineageTag: 213bcd38-8072-4373-9038-fb3402b6d51f
		summarizeBy: none
		sourceColumn: tasks.status.type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.status.orderindex'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 362bd6fb-1f7d-413c-b38c-af187a8cd367
		summarizeBy: sum
		sourceColumn: tasks.status.orderindex

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.orderindex'
		dataType: double
		isHidden
		lineageTag: b42f8b10-4a5c-4e40-abef-dbc34f859030
		summarizeBy: sum
		sourceColumn: tasks.orderindex

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'tasks.date_created'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 511dc0b3-226c-46bc-b5ec-207bcaabba92
		summarizeBy: sum
		sourceColumn: tasks.date_created

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.date_updated'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b056e2a9-52c5-4a96-af37-2c0a8cd049e9
		summarizeBy: sum
		sourceColumn: tasks.date_updated

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.date_closed'
		dataType: string
		isHidden
		lineageTag: c99a477c-e46d-4c89-9997-c16ade7f3057
		summarizeBy: none
		sourceColumn: tasks.date_closed

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.date_done'
		dataType: string
		isHidden
		lineageTag: aa71cf09-0cd1-4a67-99e3-8404cf35a63c
		summarizeBy: none
		sourceColumn: tasks.date_done

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.archived'
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 32beac36-9e1e-4659-9b11-e9be7fc7c90e
		summarizeBy: none
		sourceColumn: tasks.archived

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.creator.id'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2670b49d-3aed-4b6a-ab63-709854f57556
		summarizeBy: sum
		sourceColumn: tasks.creator.id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.creator.username'
		dataType: string
		isHidden
		lineageTag: f1d3a342-0c7a-4b69-8e3e-dc4cedb77505
		summarizeBy: none
		sourceColumn: tasks.creator.username

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.creator.color'
		dataType: string
		isHidden
		lineageTag: 8a56ff33-5e3e-480c-ba22-02a92c7f12fa
		summarizeBy: none
		sourceColumn: tasks.creator.color

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.creator.email'
		dataType: string
		isHidden
		lineageTag: 9ba13dfe-25bc-4d52-823d-c3d3484f5496
		summarizeBy: none
		sourceColumn: tasks.creator.email

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.creator.profilePicture'
		dataType: string
		isHidden
		lineageTag: 47b33791-bf82-4e10-92f6-8458ec9441df
		summarizeBy: none
		sourceColumn: tasks.creator.profilePicture

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.assignees'
		dataType: string
		isHidden
		lineageTag: 803569d5-65d1-4aa5-ae3c-ac633e8a0b28
		summarizeBy: none
		sourceColumn: tasks.assignees

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.group_assignees'
		dataType: string
		isHidden
		lineageTag: c2feeffa-f381-450d-a0a9-73a770c0c07b
		summarizeBy: none
		sourceColumn: tasks.group_assignees

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.watchers'
		dataType: string
		isHidden
		lineageTag: b4d853c0-c2ad-40dc-b1c2-51fd177e1c57
		summarizeBy: none
		sourceColumn: tasks.watchers

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.checklists'
		dataType: string
		isHidden
		lineageTag: 877a5bd1-52db-430c-99a0-8a52993e7c8a
		summarizeBy: none
		sourceColumn: tasks.checklists

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.tags'
		dataType: string
		isHidden
		lineageTag: acc95703-fdaf-4fa1-8d84-3f2c946e1d28
		summarizeBy: none
		sourceColumn: tasks.tags

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.parent'
		dataType: string
		isHidden
		lineageTag: 33fbe61d-7d89-4f71-b69b-970c2944ef54
		summarizeBy: none
		sourceColumn: tasks.parent

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.priority'
		dataType: string
		isHidden
		lineageTag: 94a7072d-328d-4222-b943-e2026ffe49d1
		summarizeBy: none
		sourceColumn: tasks.priority

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.due_date'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 09546302-fb4f-45c6-9db1-5c5d1f52715a
		summarizeBy: sum
		sourceColumn: tasks.due_date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.start_date'
		dataType: string
		isHidden
		lineageTag: d178727c-db6a-41af-a084-56b478b3dc3e
		summarizeBy: none
		sourceColumn: tasks.start_date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.points'
		dataType: string
		isHidden
		lineageTag: e929cb6b-0a0b-4a04-8f68-3188de99a616
		summarizeBy: none
		sourceColumn: tasks.points

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.time_estimate'
		dataType: string
		isHidden
		lineageTag: ba89f617-6830-4652-bea6-3501230c905d
		summarizeBy: none
		sourceColumn: tasks.time_estimate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.time_spent'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c806f661-9e4e-4085-a4cc-f4677ce0abb4
		summarizeBy: sum
		sourceColumn: tasks.time_spent

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.custom_fields'
		dataType: string
		isHidden
		lineageTag: 234c21b9-4c3e-4787-bd28-68c60071bcaf
		summarizeBy: none
		sourceColumn: tasks.custom_fields

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.dependencies'
		dataType: string
		isHidden
		lineageTag: 59d5259e-913d-444e-9a42-93f1a9c01779
		summarizeBy: none
		sourceColumn: tasks.dependencies

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.linked_tasks'
		dataType: string
		isHidden
		lineageTag: d14a7f41-06c6-435d-a622-10a4eeed3480
		summarizeBy: none
		sourceColumn: tasks.linked_tasks

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.locations'
		dataType: string
		isHidden
		lineageTag: 8e944287-e308-4b2c-a657-81a7546ee391
		summarizeBy: none
		sourceColumn: tasks.locations

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.team_id'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 1a0cbac9-4d1a-4a17-8824-09d0cc4150ae
		summarizeBy: sum
		sourceColumn: tasks.team_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.url'
		dataType: string
		isHidden
		lineageTag: f8ba35f0-0c2c-441e-8d7c-c7adba9f6cd8
		summarizeBy: none
		sourceColumn: tasks.url

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public'
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4e173819-f593-41a3-b336-b9647f8924a9
		summarizeBy: none
		sourceColumn: tasks.sharing.public

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public_share_expires_on'
		dataType: string
		isHidden
		lineageTag: c7939414-e188-4334-810c-bbb0398f367c
		summarizeBy: none
		sourceColumn: tasks.sharing.public_share_expires_on

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public_fields.0'
		dataType: string
		isHidden
		lineageTag: 683ecefa-cae0-4764-ab0b-7826b8d628db
		summarizeBy: none
		sourceColumn: tasks.sharing.public_fields.0

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public_fields.1'
		dataType: string
		isHidden
		lineageTag: d564cec4-931e-42e8-8101-8778d4b1107e
		summarizeBy: none
		sourceColumn: tasks.sharing.public_fields.1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public_fields.2'
		dataType: string
		isHidden
		lineageTag: 03a3a019-119a-4fbc-9dfb-c5ecc0c6f376
		summarizeBy: none
		sourceColumn: tasks.sharing.public_fields.2

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public_fields.3'
		dataType: string
		isHidden
		lineageTag: 4ef51e9e-f247-485f-a21d-df2bff731475
		summarizeBy: none
		sourceColumn: tasks.sharing.public_fields.3

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public_fields.4'
		dataType: string
		isHidden
		lineageTag: f78f0b97-4c63-449e-8492-68f44c78c329
		summarizeBy: none
		sourceColumn: tasks.sharing.public_fields.4

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public_fields.5'
		dataType: string
		isHidden
		lineageTag: 72442142-56ae-449c-a95f-28fb06934189
		summarizeBy: none
		sourceColumn: tasks.sharing.public_fields.5

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public_fields.6'
		dataType: string
		isHidden
		lineageTag: d82beb1f-a5b0-4172-ab3e-65d0dbce96f1
		summarizeBy: none
		sourceColumn: tasks.sharing.public_fields.6

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public_fields.7'
		dataType: string
		isHidden
		lineageTag: 6ce9ec19-5a7f-4dac-bb99-a9999c496c5e
		summarizeBy: none
		sourceColumn: tasks.sharing.public_fields.7

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public_fields.8'
		dataType: string
		isHidden
		lineageTag: 177430e8-786f-4585-a753-2755da069347
		summarizeBy: none
		sourceColumn: tasks.sharing.public_fields.8

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public_fields.9'
		dataType: string
		isHidden
		lineageTag: ea6c37c7-cb51-4b75-aebe-c47d2fcd4825
		summarizeBy: none
		sourceColumn: tasks.sharing.public_fields.9

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public_fields.10'
		dataType: string
		isHidden
		lineageTag: 0283541a-dade-4b3d-8e05-aa26d9c09564
		summarizeBy: none
		sourceColumn: tasks.sharing.public_fields.10

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.token'
		dataType: string
		isHidden
		lineageTag: a3cfdc5a-f9bd-46dc-b134-547efbe906dd
		summarizeBy: none
		sourceColumn: tasks.sharing.token

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.seo_optimized'
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c836f6db-553c-4891-9e40-a90ef13de0a5
		summarizeBy: none
		sourceColumn: tasks.sharing.seo_optimized

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.permission_level'
		dataType: string
		isHidden
		lineageTag: cab86897-f1f0-4d08-8f90-a4ae16687394
		summarizeBy: none
		sourceColumn: tasks.permission_level

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.list.id'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d1010913-bc7f-4763-8a17-214d5492fc7c
		summarizeBy: sum
		sourceColumn: tasks.list.id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.list.name'
		dataType: string
		isHidden
		lineageTag: 19d99166-dd9d-4c88-823f-14673a7a9da9
		summarizeBy: none
		sourceColumn: tasks.list.name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.list.access'
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: fcab7148-c288-4fc6-a97a-f1c35e41d28f
		summarizeBy: none
		sourceColumn: tasks.list.access

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.project.id'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: acd20247-8a8a-40ab-96c6-d17a33b15dc3
		summarizeBy: sum
		sourceColumn: tasks.project.id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.project.name'
		dataType: string
		isHidden
		lineageTag: ef63dbbd-a549-4782-bb6d-88bcdc2234fb
		summarizeBy: none
		sourceColumn: tasks.project.name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.project.hidden'
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: f0f93cb3-a52e-4c6b-a22d-4286ec741734
		summarizeBy: none
		sourceColumn: tasks.project.hidden

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.project.access'
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: f39fac19-698c-4387-886c-05d884296cdf
		summarizeBy: none
		sourceColumn: tasks.project.access

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.folder.id'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ca4d8084-d053-4e84-a11c-1902a8a8136e
		summarizeBy: sum
		sourceColumn: tasks.folder.id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.folder.name'
		dataType: string
		isHidden
		lineageTag: 549b71d2-de4b-4817-91c4-bf454a205504
		summarizeBy: none
		sourceColumn: tasks.folder.name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.folder.hidden'
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: bb7cc9d5-585b-44f9-a7f1-8bf84fff825e
		summarizeBy: none
		sourceColumn: tasks.folder.hidden

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.folder.access'
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: cd283331-16ab-420f-a766-aae2bc34565f
		summarizeBy: none
		sourceColumn: tasks.folder.access

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.space.id'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 9d86cae9-eaac-421b-bf02-7114fb6d35ad
		summarizeBy: sum
		sourceColumn: tasks.space.id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column last_page
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e87f880f-ecb2-4100-be7e-d7e612164b54
		summarizeBy: none
		sourceColumn: last_page

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Cognitive Research Corporation' = m
		mode: import
		source =
				let
				    Source = Json.Document(Web.Contents("https://api.clickup.com/api/v2/list/901405803973/task?archived=false&include_closed=true", [Headers=[Authorization="pk_82352337_MW1MWBNX1HM4ATHKLLRXPX11IAC7WGA8"]])),
				    #"Converted to Table" = Table.FromRecords({Source}),
				    #"Expanded tasks" = Table.ExpandListColumn(#"Converted to Table", "tasks"),
				    #"Expanded tasks1" = Table.ExpandRecordColumn(#"Expanded tasks", "tasks", {"id", "custom_id", "custom_item_id", "name", "text_content", "description", "status", "orderindex", "date_created", "date_updated", "date_closed", "date_done", "archived", "creator", "assignees", "group_assignees", "watchers", "checklists", "tags", "parent", "priority", "due_date", "start_date", "points", "time_estimate", "time_spent", "custom_fields", "dependencies", "linked_tasks", "locations", "team_id", "url", "sharing", "permission_level", "list", "project", "folder", "space"}, {"tasks.id", "tasks.custom_id", "tasks.custom_item_id", "tasks.name", "tasks.text_content", "tasks.description", "tasks.status", "tasks.orderindex", "tasks.date_created", "tasks.date_updated", "tasks.date_closed", "tasks.date_done", "tasks.archived", "tasks.creator", "tasks.assignees", "tasks.group_assignees", "tasks.watchers", "tasks.checklists", "tasks.tags", "tasks.parent", "tasks.priority", "tasks.due_date", "tasks.start_date", "tasks.points", "tasks.time_estimate", "tasks.time_spent", "tasks.custom_fields", "tasks.dependencies", "tasks.linked_tasks", "tasks.locations", "tasks.team_id", "tasks.url", "tasks.sharing", "tasks.permission_level", "tasks.list", "tasks.project", "tasks.folder", "tasks.space"}),
				    #"Expanded tasks.status" = Table.ExpandRecordColumn(#"Expanded tasks1", "tasks.status", {"status", "id", "color", "type", "orderindex"}, {"tasks.status.status", "tasks.status.id", "tasks.status.color", "tasks.status.type", "tasks.status.orderindex"}),
				    #"Expanded tasks.creator" = Table.ExpandRecordColumn(#"Expanded tasks.status", "tasks.creator", {"id", "username", "color", "email", "profilePicture"}, {"tasks.creator.id", "tasks.creator.username", "tasks.creator.color", "tasks.creator.email", "tasks.creator.profilePicture"}),
				    #"Expanded tasks.sharing" = Table.ExpandRecordColumn(#"Expanded tasks.creator", "tasks.sharing", {"public", "public_share_expires_on", "public_fields", "token", "seo_optimized"}, {"tasks.sharing.public", "tasks.sharing.public_share_expires_on", "tasks.sharing.public_fields", "tasks.sharing.token", "tasks.sharing.seo_optimized"}),
				    #"Split Column" = Table.SplitColumn(#"Expanded tasks.sharing", "tasks.sharing.public_fields", each _, {"tasks.sharing.public_fields.0", "tasks.sharing.public_fields.1", "tasks.sharing.public_fields.2", "tasks.sharing.public_fields.3", "tasks.sharing.public_fields.4", "tasks.sharing.public_fields.5", "tasks.sharing.public_fields.6", "tasks.sharing.public_fields.7", "tasks.sharing.public_fields.8", "tasks.sharing.public_fields.9", "tasks.sharing.public_fields.10"}),
				    #"Expanded tasks.list" = Table.ExpandRecordColumn(#"Split Column", "tasks.list", {"id", "name", "access"}, {"tasks.list.id", "tasks.list.name", "tasks.list.access"}),
				    #"Expanded tasks.project" = Table.ExpandRecordColumn(#"Expanded tasks.list", "tasks.project", {"id", "name", "hidden", "access"}, {"tasks.project.id", "tasks.project.name", "tasks.project.hidden", "tasks.project.access"}),
				    #"Expanded tasks.folder" = Table.ExpandRecordColumn(#"Expanded tasks.project", "tasks.folder", {"id", "name", "hidden", "access"}, {"tasks.folder.id", "tasks.folder.name", "tasks.folder.hidden", "tasks.folder.access"}),
				    #"Expanded tasks.space" = Table.ExpandRecordColumn(#"Expanded tasks.folder", "tasks.space", {"id"}, {"tasks.space.id"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded tasks.space",{{"tasks.id", type text}, {"tasks.custom_id", type any}, {"tasks.custom_item_id", Int64.Type}, {"tasks.name", type text}, {"tasks.text_content", type text}, {"tasks.description", type text}, {"tasks.status.status", type text}, {"tasks.status.id", type text}, {"tasks.status.color", type text}, {"tasks.status.type", type text}, {"tasks.status.orderindex", Int64.Type}, {"tasks.orderindex", type number}, {"tasks.date_created", Int64.Type}, {"tasks.date_updated", Int64.Type}, {"tasks.date_closed", type any}, {"tasks.date_done", type any}, {"tasks.archived", type logical}, {"tasks.creator.id", Int64.Type}, {"tasks.creator.username", type text}, {"tasks.creator.color", type text}, {"tasks.creator.email", type text}, {"tasks.creator.profilePicture", type any}, {"tasks.assignees", type any}, {"tasks.group_assignees", type any}, {"tasks.watchers", type any}, {"tasks.checklists", type any}, {"tasks.tags", type any}, {"tasks.parent", type any}, {"tasks.priority", type any}, {"tasks.due_date", Int64.Type}, {"tasks.start_date", type any}, {"tasks.points", type any}, {"tasks.time_estimate", type any}, {"tasks.time_spent", Int64.Type}, {"tasks.custom_fields", type any}, {"tasks.dependencies", type any}, {"tasks.linked_tasks", type any}, {"tasks.locations", type any}, {"tasks.team_id", Int64.Type}, {"tasks.url", type text}, {"tasks.sharing.public", type logical}, {"tasks.sharing.public_share_expires_on", type any}, {"tasks.sharing.public_fields.0", type text}, {"tasks.sharing.public_fields.1", type text}, {"tasks.sharing.public_fields.2", type text}, {"tasks.sharing.public_fields.3", type text}, {"tasks.sharing.public_fields.4", type text}, {"tasks.sharing.public_fields.5", type text}, {"tasks.sharing.public_fields.6", type text}, {"tasks.sharing.public_fields.7", type text}, {"tasks.sharing.public_fields.8", type text}, {"tasks.sharing.public_fields.9", type text}, {"tasks.sharing.public_fields.10", type text}, {"tasks.sharing.token", type any}, {"tasks.sharing.seo_optimized", type logical}, {"tasks.permission_level", type text}, {"tasks.list.id", Int64.Type}, {"tasks.list.name", type text}, {"tasks.list.access", type logical}, {"tasks.project.id", Int64.Type}, {"tasks.project.name", type text}, {"tasks.project.hidden", type logical}, {"tasks.project.access", type logical}, {"tasks.folder.id", Int64.Type}, {"tasks.folder.name", type text}, {"tasks.folder.hidden", type logical}, {"tasks.folder.access", type logical}, {"tasks.space.id", Int64.Type}, {"last_page", type logical}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

