table 'Lansing Water & Electric'
	isHidden
	lineageTag: 8dbb893b-2ae0-497a-9a41-398691c07fb1

	column 'tasks.id'
		dataType: string
		isHidden
		lineageTag: a48711c0-7ece-4273-8cf1-da545f356b0c
		summarizeBy: none
		sourceColumn: tasks.id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.custom_id'
		dataType: string
		isHidden
		lineageTag: 4a7ffaf2-f8f0-4a70-a12f-407e722fe55a
		summarizeBy: none
		sourceColumn: tasks.custom_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.custom_item_id'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: dea2d647-72da-410b-9f33-e35ed18bd558
		summarizeBy: sum
		sourceColumn: tasks.custom_item_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.name'
		dataType: string
		isHidden
		lineageTag: 699672ab-74e1-4e9b-ad34-68cf3c9e91f1
		summarizeBy: none
		sourceColumn: tasks.name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.text_content'
		dataType: string
		isHidden
		lineageTag: bd37c6dd-3410-4ef3-b661-3cdd18e25321
		summarizeBy: none
		sourceColumn: tasks.text_content

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.description'
		dataType: string
		isHidden
		lineageTag: e8adc488-3cd0-4c6e-88f9-f9546a4fd861
		summarizeBy: none
		sourceColumn: tasks.description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.status.status'
		dataType: string
		isHidden
		lineageTag: 239c7acc-125b-43f8-81c2-17688b6b4587
		summarizeBy: none
		sourceColumn: tasks.status.status

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.status.id'
		dataType: string
		isHidden
		lineageTag: 407811b9-de5d-413d-9449-970f239a0c91
		summarizeBy: none
		sourceColumn: tasks.status.id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.status.color'
		dataType: string
		isHidden
		lineageTag: 78221458-3a5b-4c66-8d3f-456b50c28b5b
		summarizeBy: none
		sourceColumn: tasks.status.color

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.status.type'
		dataType: string
		isHidden
		lineageTag: 424cc2f2-cb30-4a2b-a8f4-db0ff2442de1
		summarizeBy: none
		sourceColumn: tasks.status.type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.status.orderindex'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 013f6565-fd3b-4b30-b1d7-4a4c8121456d
		summarizeBy: sum
		sourceColumn: tasks.status.orderindex

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.orderindex'
		dataType: double
		isHidden
		lineageTag: 9ac8ffef-e66f-4b9d-8e9c-b2226d86b719
		summarizeBy: sum
		sourceColumn: tasks.orderindex

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'tasks.date_created'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 76915dbb-56b2-496a-b2c9-97340f7a54a6
		summarizeBy: sum
		sourceColumn: tasks.date_created

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.date_updated'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c43ffcdb-8cf6-418c-9898-1e1abf031dca
		summarizeBy: sum
		sourceColumn: tasks.date_updated

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.date_closed'
		dataType: string
		isHidden
		lineageTag: 8c0732ad-fa22-4b8a-8ee6-6c1df4d80695
		summarizeBy: none
		sourceColumn: tasks.date_closed

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.date_done'
		dataType: string
		isHidden
		lineageTag: cecb849d-3e07-49df-9d3f-cb23c9fd94de
		summarizeBy: none
		sourceColumn: tasks.date_done

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.archived'
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 46df20a9-c075-4a07-a80f-7d4780383b93
		summarizeBy: none
		sourceColumn: tasks.archived

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.creator.id'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 02ba1227-054e-4075-b287-9d92affeac3c
		summarizeBy: sum
		sourceColumn: tasks.creator.id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.creator.username'
		dataType: string
		isHidden
		lineageTag: 166b236e-9703-4dc1-9c12-9c9de784da51
		summarizeBy: none
		sourceColumn: tasks.creator.username

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.creator.color'
		dataType: string
		isHidden
		lineageTag: 43aa02c5-46f2-49e8-b6d5-d90f02cf0e59
		summarizeBy: none
		sourceColumn: tasks.creator.color

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.creator.email'
		dataType: string
		isHidden
		lineageTag: b1128176-34ef-4055-a094-b53cc3e2fc50
		summarizeBy: none
		sourceColumn: tasks.creator.email

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.creator.profilePicture'
		dataType: string
		isHidden
		lineageTag: c929245a-126b-45b8-8c0f-73c3939bcd90
		summarizeBy: none
		sourceColumn: tasks.creator.profilePicture

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.assignees'
		dataType: string
		isHidden
		lineageTag: 1723e4eb-233d-4202-82d8-845051c743e4
		summarizeBy: none
		sourceColumn: tasks.assignees

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.group_assignees'
		dataType: string
		isHidden
		lineageTag: 5e11553a-be25-4038-add7-b1ad5e42a2f3
		summarizeBy: none
		sourceColumn: tasks.group_assignees

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.watchers'
		dataType: string
		isHidden
		lineageTag: da4b7c1d-4963-4fd0-a6ef-9bd2b3f23c30
		summarizeBy: none
		sourceColumn: tasks.watchers

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.checklists'
		dataType: string
		isHidden
		lineageTag: 00d6dbbb-62d4-4f46-adba-37c608706e66
		summarizeBy: none
		sourceColumn: tasks.checklists

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.tags'
		dataType: string
		isHidden
		lineageTag: ce66848c-5185-41b5-b632-c355f78e109b
		summarizeBy: none
		sourceColumn: tasks.tags

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.parent'
		dataType: string
		isHidden
		lineageTag: ca03a450-5cde-4606-ab53-dddba3233fa8
		summarizeBy: none
		sourceColumn: tasks.parent

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.priority'
		dataType: string
		isHidden
		lineageTag: d0e6373a-0996-44c7-b075-8a0a1ec157fb
		summarizeBy: none
		sourceColumn: tasks.priority

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.due_date'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: cc7aeeea-9ac0-411b-9e8f-9b5b1f8eefcf
		summarizeBy: sum
		sourceColumn: tasks.due_date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.start_date'
		dataType: string
		isHidden
		lineageTag: a6da10b9-c5b1-4db1-acf6-d2725097ed2e
		summarizeBy: none
		sourceColumn: tasks.start_date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.points'
		dataType: string
		isHidden
		lineageTag: ec0c0f05-54f6-4702-8d52-05e61d5ec42b
		summarizeBy: none
		sourceColumn: tasks.points

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.time_estimate'
		dataType: string
		isHidden
		lineageTag: 93bf00af-3a0e-4d1f-8d22-3db0171664b3
		summarizeBy: none
		sourceColumn: tasks.time_estimate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.time_spent'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 44c9428d-6408-4f1a-a737-9b00895724e3
		summarizeBy: sum
		sourceColumn: tasks.time_spent

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.custom_fields'
		dataType: string
		isHidden
		lineageTag: b55e877d-84ce-48ec-a0db-1b6fdf7bff7e
		summarizeBy: none
		sourceColumn: tasks.custom_fields

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.dependencies'
		dataType: string
		isHidden
		lineageTag: ddf5f360-d648-4e84-b830-2bfda700ef6d
		summarizeBy: none
		sourceColumn: tasks.dependencies

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.linked_tasks'
		dataType: string
		isHidden
		lineageTag: 7315cb00-460e-4663-8807-82e75ce8ed60
		summarizeBy: none
		sourceColumn: tasks.linked_tasks

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.locations'
		dataType: string
		isHidden
		lineageTag: c965d21f-5fba-454c-9d28-0c27939b94a3
		summarizeBy: none
		sourceColumn: tasks.locations

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.team_id'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 98e8229f-4b20-47f6-b30e-e4b26b31c1df
		summarizeBy: sum
		sourceColumn: tasks.team_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.url'
		dataType: string
		isHidden
		lineageTag: bb9dfa42-ee49-4253-8740-2ebd2e6a955c
		summarizeBy: none
		sourceColumn: tasks.url

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public'
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: b9542b78-785d-44e5-b72a-b26722d31e99
		summarizeBy: none
		sourceColumn: tasks.sharing.public

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public_share_expires_on'
		dataType: string
		isHidden
		lineageTag: 77a69620-24f0-438c-b16e-0a96fd7876a4
		summarizeBy: none
		sourceColumn: tasks.sharing.public_share_expires_on

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public_fields.0'
		dataType: string
		isHidden
		lineageTag: 95f42a6a-e19c-4b1c-bc3a-a319621f9578
		summarizeBy: none
		sourceColumn: tasks.sharing.public_fields.0

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public_fields.1'
		dataType: string
		isHidden
		lineageTag: 8b782dce-01bd-47cc-bedf-5675e9bc477d
		summarizeBy: none
		sourceColumn: tasks.sharing.public_fields.1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public_fields.2'
		dataType: string
		isHidden
		lineageTag: 4610c1e3-8cec-40c5-9af5-43a4d68e487c
		summarizeBy: none
		sourceColumn: tasks.sharing.public_fields.2

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public_fields.3'
		dataType: string
		isHidden
		lineageTag: c7f744a2-175d-48cf-8f24-47838f2747a8
		summarizeBy: none
		sourceColumn: tasks.sharing.public_fields.3

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public_fields.4'
		dataType: string
		isHidden
		lineageTag: 5939df45-b7c3-437f-97b4-7e8fa923f013
		summarizeBy: none
		sourceColumn: tasks.sharing.public_fields.4

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public_fields.5'
		dataType: string
		isHidden
		lineageTag: f6a769be-b252-4485-9805-3987d78dcd93
		summarizeBy: none
		sourceColumn: tasks.sharing.public_fields.5

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public_fields.6'
		dataType: string
		isHidden
		lineageTag: 1787a9a0-4544-4a8b-ba05-ac61c18b9f1c
		summarizeBy: none
		sourceColumn: tasks.sharing.public_fields.6

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public_fields.7'
		dataType: string
		isHidden
		lineageTag: 9b2e2b3e-0d4e-4694-9fdf-5fdfb7ca0ed0
		summarizeBy: none
		sourceColumn: tasks.sharing.public_fields.7

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public_fields.8'
		dataType: string
		isHidden
		lineageTag: 9dda6979-7ca3-4660-85f6-6f6a20a2f56b
		summarizeBy: none
		sourceColumn: tasks.sharing.public_fields.8

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public_fields.9'
		dataType: string
		isHidden
		lineageTag: 6b369131-8355-4f2e-8ced-8dbbce669340
		summarizeBy: none
		sourceColumn: tasks.sharing.public_fields.9

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.public_fields.10'
		dataType: string
		isHidden
		lineageTag: b5a0db8f-61a1-49d9-a41f-4a152f8fd885
		summarizeBy: none
		sourceColumn: tasks.sharing.public_fields.10

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.token'
		dataType: string
		isHidden
		lineageTag: d5194a1a-9f58-4ecd-a60a-f77bd6552028
		summarizeBy: none
		sourceColumn: tasks.sharing.token

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.sharing.seo_optimized'
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 67632bd5-a2e1-41ef-be77-b27ecc9d4209
		summarizeBy: none
		sourceColumn: tasks.sharing.seo_optimized

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.permission_level'
		dataType: string
		isHidden
		lineageTag: 24a3942f-6301-4249-a612-b5826df2194c
		summarizeBy: none
		sourceColumn: tasks.permission_level

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.list.id'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 0ca99eed-b1db-41b6-9a08-d48b649e6c5f
		summarizeBy: sum
		sourceColumn: tasks.list.id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.list.name'
		dataType: string
		isHidden
		lineageTag: 587aa097-8681-4fc5-bc6f-6af67146a415
		summarizeBy: none
		sourceColumn: tasks.list.name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.list.access'
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 11a2e6e5-488e-44ff-8ed7-c87a29887b88
		summarizeBy: none
		sourceColumn: tasks.list.access

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.project.id'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 10db4ea9-1e37-44fd-8c1d-187a2e3b2480
		summarizeBy: sum
		sourceColumn: tasks.project.id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.project.name'
		dataType: string
		isHidden
		lineageTag: 6a4b7bf2-f8cf-41d5-909d-53bed02a56b3
		summarizeBy: none
		sourceColumn: tasks.project.name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.project.hidden'
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: f1f5556a-055f-48f8-b867-0912d4a0811e
		summarizeBy: none
		sourceColumn: tasks.project.hidden

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.project.access'
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c50ec559-21c4-4af3-9dd3-924036c67718
		summarizeBy: none
		sourceColumn: tasks.project.access

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.folder.id'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 1a8ed094-6f89-4196-97d3-ddfe8d637516
		summarizeBy: sum
		sourceColumn: tasks.folder.id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.folder.name'
		dataType: string
		isHidden
		lineageTag: 47f94775-5416-40fc-96fc-fb24371d056c
		summarizeBy: none
		sourceColumn: tasks.folder.name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.folder.hidden'
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ca1fb804-9184-4663-a543-176c8f48ff26
		summarizeBy: none
		sourceColumn: tasks.folder.hidden

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.folder.access'
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: f03d9679-d68a-40ba-bf17-b8b3857ceb2e
		summarizeBy: none
		sourceColumn: tasks.folder.access

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'tasks.space.id'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c88ebfed-1b59-4dde-8172-f626a82fda4b
		summarizeBy: sum
		sourceColumn: tasks.space.id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column last_page
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 84f94dc1-0ee7-4a59-a4b6-7516699ccce0
		summarizeBy: none
		sourceColumn: last_page

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Lansing Water & Electric' = m
		mode: import
		source =
				let
				    Source = Json.Document(Web.Contents("https://api.clickup.com/api/v2/list/901404714988/task?archived=false&include_closed=true", [Headers=[Authorization="pk_82352337_MW1MWBNX1HM4ATHKLLRXPX11IAC7WGA8"]])),
				    #"Converted to Table" = Table.FromRecords({Source}),
				    #"Expanded tasks" = Table.ExpandListColumn(#"Converted to Table", "tasks"),
				    #"Expanded tasks1" = Table.ExpandRecordColumn(#"Expanded tasks", "tasks", {"id", "custom_id", "custom_item_id", "name", "text_content", "description", "status", "orderindex", "date_created", "date_updated", "date_closed", "date_done", "archived", "creator", "assignees", "group_assignees", "watchers", "checklists", "tags", "parent", "priority", "due_date", "start_date", "points", "time_estimate", "time_spent", "custom_fields", "dependencies", "linked_tasks", "locations", "team_id", "url", "sharing", "permission_level", "list", "project", "folder", "space"}, {"tasks.id", "tasks.custom_id", "tasks.custom_item_id", "tasks.name", "tasks.text_content", "tasks.description", "tasks.status", "tasks.orderindex", "tasks.date_created", "tasks.date_updated", "tasks.date_closed", "tasks.date_done", "tasks.archived", "tasks.creator", "tasks.assignees", "tasks.group_assignees", "tasks.watchers", "tasks.checklists", "tasks.tags", "tasks.parent", "tasks.priority", "tasks.due_date", "tasks.start_date", "tasks.points", "tasks.time_estimate", "tasks.time_spent", "tasks.custom_fields", "tasks.dependencies", "tasks.linked_tasks", "tasks.locations", "tasks.team_id", "tasks.url", "tasks.sharing", "tasks.permission_level", "tasks.list", "tasks.project", "tasks.folder", "tasks.space"}),
				    #"Expanded tasks.status" = Table.ExpandRecordColumn(#"Expanded tasks1", "tasks.status", {"status", "id", "color", "type", "orderindex"}, {"tasks.status.status", "tasks.status.id", "tasks.status.color", "tasks.status.type", "tasks.status.orderindex"}),
				    #"Expanded tasks.creator" = Table.ExpandRecordColumn(#"Expanded tasks.status", "tasks.creator", {"id", "username", "color", "email", "profilePicture"}, {"tasks.creator.id", "tasks.creator.username", "tasks.creator.color", "tasks.creator.email", "tasks.creator.profilePicture"}),
				    #"Expanded tasks.sharing" = Table.ExpandRecordColumn(#"Expanded tasks.creator", "tasks.sharing", {"public", "public_share_expires_on", "public_fields", "token", "seo_optimized"}, {"tasks.sharing.public", "tasks.sharing.public_share_expires_on", "tasks.sharing.public_fields", "tasks.sharing.token", "tasks.sharing.seo_optimized"}),
				    #"Split Column" = Table.SplitColumn(#"Expanded tasks.sharing", "tasks.sharing.public_fields", each _, {"tasks.sharing.public_fields.0", "tasks.sharing.public_fields.1", "tasks.sharing.public_fields.2", "tasks.sharing.public_fields.3", "tasks.sharing.public_fields.4", "tasks.sharing.public_fields.5", "tasks.sharing.public_fields.6", "tasks.sharing.public_fields.7", "tasks.sharing.public_fields.8", "tasks.sharing.public_fields.9", "tasks.sharing.public_fields.10"}),
				    #"Expanded tasks.list" = Table.ExpandRecordColumn(#"Split Column", "tasks.list", {"id", "name", "access"}, {"tasks.list.id", "tasks.list.name", "tasks.list.access"}),
				    #"Expanded tasks.project" = Table.ExpandRecordColumn(#"Expanded tasks.list", "tasks.project", {"id", "name", "hidden", "access"}, {"tasks.project.id", "tasks.project.name", "tasks.project.hidden", "tasks.project.access"}),
				    #"Expanded tasks.folder" = Table.ExpandRecordColumn(#"Expanded tasks.project", "tasks.folder", {"id", "name", "hidden", "access"}, {"tasks.folder.id", "tasks.folder.name", "tasks.folder.hidden", "tasks.folder.access"}),
				    #"Expanded tasks.space" = Table.ExpandRecordColumn(#"Expanded tasks.folder", "tasks.space", {"id"}, {"tasks.space.id"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded tasks.space",{{"tasks.id", type text}, {"tasks.custom_id", type any}, {"tasks.custom_item_id", Int64.Type}, {"tasks.name", type text}, {"tasks.text_content", type text}, {"tasks.description", type text}, {"tasks.status.status", type text}, {"tasks.status.id", type text}, {"tasks.status.color", type text}, {"tasks.status.type", type text}, {"tasks.status.orderindex", Int64.Type}, {"tasks.orderindex", type number}, {"tasks.date_created", Int64.Type}, {"tasks.date_updated", Int64.Type}, {"tasks.date_closed", type any}, {"tasks.date_done", type any}, {"tasks.archived", type logical}, {"tasks.creator.id", Int64.Type}, {"tasks.creator.username", type text}, {"tasks.creator.color", type text}, {"tasks.creator.email", type text}, {"tasks.creator.profilePicture", type any}, {"tasks.assignees", type any}, {"tasks.group_assignees", type any}, {"tasks.watchers", type any}, {"tasks.checklists", type any}, {"tasks.tags", type any}, {"tasks.parent", type any}, {"tasks.priority", type any}, {"tasks.due_date", Int64.Type}, {"tasks.start_date", type any}, {"tasks.points", type any}, {"tasks.time_estimate", type any}, {"tasks.time_spent", Int64.Type}, {"tasks.custom_fields", type any}, {"tasks.dependencies", type any}, {"tasks.linked_tasks", type any}, {"tasks.locations", type any}, {"tasks.team_id", Int64.Type}, {"tasks.url", type text}, {"tasks.sharing.public", type logical}, {"tasks.sharing.public_share_expires_on", type any}, {"tasks.sharing.public_fields.0", type text}, {"tasks.sharing.public_fields.1", type text}, {"tasks.sharing.public_fields.2", type text}, {"tasks.sharing.public_fields.3", type text}, {"tasks.sharing.public_fields.4", type text}, {"tasks.sharing.public_fields.5", type text}, {"tasks.sharing.public_fields.6", type text}, {"tasks.sharing.public_fields.7", type text}, {"tasks.sharing.public_fields.8", type text}, {"tasks.sharing.public_fields.9", type text}, {"tasks.sharing.public_fields.10", type text}, {"tasks.sharing.token", type any}, {"tasks.sharing.seo_optimized", type logical}, {"tasks.permission_level", type text}, {"tasks.list.id", Int64.Type}, {"tasks.list.name", type text}, {"tasks.list.access", type logical}, {"tasks.project.id", Int64.Type}, {"tasks.project.name", type text}, {"tasks.project.hidden", type logical}, {"tasks.project.access", type logical}, {"tasks.folder.id", Int64.Type}, {"tasks.folder.name", type text}, {"tasks.folder.hidden", type logical}, {"tasks.folder.access", type logical}, {"tasks.space.id", Int64.Type}, {"last_page", type logical}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

