table Invoicing
	lineageTag: 2fecac1e-b3a1-4e0b-9ad2-0cdf272d87aa

	column Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 3a93fb4f-035e-4f2c-8a8b-30544650033c
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Transaction type'
		dataType: string
		lineageTag: f3128ad7-f50b-4923-9d01-8dfa894c5e63
		summarizeBy: none
		sourceColumn: Transaction type

		annotation SummarizationSetBy = Automatic

	column Num
		dataType: int64
		formatString: 0
		lineageTag: 2c7214d5-b40a-4365-a76b-a0c40f2ab826
		summarizeBy: sum
		sourceColumn: Num

		annotation SummarizationSetBy = Automatic

	column 'Project Name'
		dataType: string
		lineageTag: a84b65f6-0b3d-4092-91b0-30c5f4904f8b
		summarizeBy: none
		sourceColumn: Project Name

		annotation SummarizationSetBy = Automatic

	column Memo/Description
		dataType: string
		lineageTag: 7fdc8840-ea53-41ed-a827-df690b965687
		summarizeBy: none
		sourceColumn: Memo/Description

		annotation SummarizationSetBy = Automatic

	column Amount
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 5240c579-9c79-44b9-bf22-c47294fe96d3
		summarizeBy: sum
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Due date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 7bbed257-8ec1-4d94-b2d7-520451158e87
		summarizeBy: none
		sourceColumn: Due date

		variation Variation
			isDefault
			relationship: 8382fb16-7b40-4ff6-af27-c79f4029e8a1
			defaultHierarchy: LocalDateTable_abef62f3-8aa8-4509-870a-71cabd5fdd11.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Open balance'
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: e4807bb0-df6d-43ca-a960-2542ffd5cbcb
		summarizeBy: sum
		sourceColumn: Open balance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	partition Invoicing = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\BrandonA\OneDrive - BI Consulting Services\Documents\BICS Internal Work\Copy of Invoice List by Date (Brandons Copy).xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"BI Consulting Services, LLC", type any}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type any}, {"Column7", type any}, {"Column8", type any}}),
				    #"Removed Top Rows" = Table.Skip(#"Changed Type",3),
				    #"Promoted Headers1" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers1",{{"Date", type date}, {"Transaction type", type text}, {"Num", Int64.Type}, {"Name", type text}, {"Memo/Description", type text}, {"Due date", type date}, {"Amount", type number}, {"Open balance", type number}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"Name", "Project Name"}}),
				    #"Removed Bottom Rows" = Table.RemoveLastN(#"Renamed Columns",5)
				in
				    #"Removed Bottom Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

